# Generated by Django 4.2 on 2023-04-18 09:10

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(null=True, upload_to='product_categories')),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('description', django_quill.fields.QuillField(null=True)),
            ],
        ),
    ]
