# Generated by Django 4.2 on 2023-04-19 02:43

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_productcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('slug', models.SlugField(editable=False)),
                ('short_description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Short Description')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size')),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_categories/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcategory', verbose_name='Product Category'),
        ),
    ]
