# Generated by Django 4.2 on 2023-04-19 03:28

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_productcategory_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True)),
                ('short_description', django_quill.fields.QuillField(blank=True, verbose_name='Short Description')),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('published_date', models.DateTimeField()),
                ('description', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description')),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GridBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='grid_banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150)),
                ('published_date', models.DateTimeField()),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='notices/')),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.blog')),
            ],
        ),
    ]
