# Generated by Django 4.2 on 2023-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_banner_blog_gridbanner_notice_blogtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('email', models.EmailField(max_length=200)),
                ('google_map_location', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(editable=False, max_length=150),
        ),
    ]
