# Generated by Django 4.2 on 2023-04-20 08:53

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_feedbacks_siteinfo_alter_blog_slug_alter_notice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterField(
            model_name='gridbanner',
            name='image',
            field=models.ImageField(help_text='The image size 570 * 270 px', upload_to='grid_banners/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, help_text='The image size should be 600 * 500', upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='The image size should be 270 * 230 px', null=True, upload_to='product_categories/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='The image size should be 270 * 270 px', upload_to='products/'),
        ),
    ]
