# Generated by Django 4.2 on 2023-04-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_about_alter_feedbacks_options_alter_gridbanner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('hot', 'Hot'), ('upcomming', 'Upcomming')], default='normal', max_length=10),
        ),
    ]
